import { defineField, defineType } from "sanity";

export const skinIngredientSchema = defineType({
  name: "skinIngredient",
  title: "Skin Ingredients",
  type: "document",
  fields: [
    defineField({ name: "title", title: "Ingredient Name", type: "string", validation: (r) => r.required() }),
    defineField({ name: "slug", title: "Slug", type: "slug", options: { source: "title" }, validation: (r) => r.required() }),
    defineField({ name: "description", title: "Short Description", type: "text", rows: 3 }),
    defineField({ name: "category", title: "Category", type: "string",
      options: { list: ["Antioxidant", "Exfoliant", "Humectant", "Emollient", "Retinoid", "SPF", "Peptide", "Other"] },
    }),
    defineField({ name: "evidenceLevel", title: "Evidence Level", type: "string",
      options: { list: ["strong", "moderate", "limited", "emerging", "insufficient"] },
    }),
    defineField({
      name: "skinTypes", title: "Suitable Skin Types", type: "array",
      of: [{ type: "string" }],
      options: { list: ["oily", "dry", "combination", "sensitive", "normal", "acne-prone", "mature"] },
    }),
    defineField({ name: "benefits", title: "Benefits", type: "array", of: [{ type: "string" }] }),
    defineField({ name: "risks", title: "Risks / Warnings", type: "array", of: [{ type: "string" }] }),
    defineField({ name: "howToUse", title: "How To Use", type: "text", rows: 3 }),
    defineField({ name: "sources", title: "Scientific Sources", type: "array", of: [{ type: "string" }],
      description: "Cite as: Author (Year). Title. Journal. DOI or URL.",
    }),
    defineField({ name: "body", title: "Full Content", type: "array",
      of: [{ type: "block" }, { type: "image" }],
    }),
    defineField({ name: "metaDescription", title: "Meta Description", type: "text", rows: 2,
      description: "For SEO — keep under 155 characters",
    }),
    defineField({ name: "publishedAt", title: "Published Date", type: "date" }),
  ],
  preview: { select: { title: "title", subtitle: "category" } },
});
